version: '3.0'

services:
  server:
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    restart: always
    ports:
      - 3344:3344
    volumes:
      - ../:/srv
      - redis_run:/run/redis
    environment:
      ENV: development
      LOG_FILE: /dev/stdout
      LOG_LEVEL: debug
      HOST: 0.0.0.0
      PORT: 3344
      REDIS_URL: unix:///run/redis/redis.sock
    depends_on:
      - redis

  admin:
    build:
      context: ../
      dockerfile: docker/admin/Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ../:/srv
      - redis_run:/run/redis
    environment:
      ENV: development
      REDIS_URL: unix:///run/redis/redis.sock
    depends_on:
      - redis

  resque:
    build:
      context: ../
      dockerfile: docker/resque/Dockerfile
    restart: always
    volumes:
      - ../:/srv
      - redis_run:/run/redis
    environment:
      QUEUE: '*'
      COUNT: 1
      REDIS_URL: unix:///run/redis/redis.sock
    depends_on:
      - redis

  redis:
    build: redis
    restart: always
    command: redis-server /redis.conf
    volumes:
      - redis_run:/run/redis

volumes:
  redis_run:
    driver: local
