source 'https://rubygems.org'

# Padrino supports Ruby version 2.2.2 and later
# ruby '2.6.5'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'activesupport', '>= 3.1'
gem 'bcrypt'

gem 'ohm', '~> 3.1'
gem "ohm-contrib", "~> 3"
gem "ohm-validations"

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.14.4'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.14.4'
# end
